version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.2.0
  shellcheck: circleci/shellcheck@3.1.1

aliases:
  - &common-config
    context: global
    orb-name: entur/grafana-sync-orb
    vcs-type: github
    enable-pr-comment: false

workflows:
  verify:
    jobs:
      - orb-tools/lint:
          name: lint
      - orb-tools/pack:
          name: pack
          source-dir: src
      - orb-tools/review:
          name: review
      - shellcheck/check:
          name: shellcheck
          dir: src/scripts
      - orb-tools/publish:
          name: publish
          <<: *common-config
          filters:
            branches:
              ignore: main
          requires:
            - pack
      - orb-tools/publish:
          name: release
          <<: *common-config
          filters:
            branches:
              only: main
          pub-type: production
          requires:
            - lint
            - pack
            - review
            - shellcheck
