version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.3.0
  shellcheck: circleci/shellcheck@3.1.1

aliases:
  - &common-config
    context: global
    orb-name: entur/grafana-sync-orb
    vcs-type: github
    enable-pr-comment: false

  - &deploy-filter
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v.*/

jobs:
  get-tag:
    executor: orb-tools/default
    steps:
      - checkout
      - run: |
          LATEST_TAG="$(git describe --tags --abbrev=0 HEAD)"
          echo "Latest tag: $LATEST_TAG"
          echo "export CIRCLE_TAG=\"$LATEST_TAG\"" >> "$BASH_ENV"

workflows:
  verify:
    jobs:
      - orb-tools/lint:
          name: lint
      - orb-tools/pack:
          name: pack
          source-dir: src
      - orb-tools/review:
          name: review
      - shellcheck/check:
          name: shellcheck
          dir: src/scripts
      - orb-tools/publish:
          name: publish
          <<: *common-config
          filters:
            branches:
              ignore: main
          requires:
            - pack

  publish:
    jobs:
      - orb-tools/lint:
          name: lint
          <<: *deploy-filter
      - orb-tools/pack:
          name: pack
          source-dir: src
          <<: *deploy-filter
      - orb-tools/review:
          name: review
          <<: *deploy-filter
      - shellcheck/check:
          name: shellcheck
          dir: src/scripts
          <<: *deploy-filter
      - orb-tools/publish:
          name: release
          <<: *common-config
          <<: *deploy-filter
          pub-type: production
          requires:
            - lint
            - pack
            - review
            - shellcheck
